### ISSUE TITLE
Change PVDR to AVAR in neuron.txt

### ISSUE THREAD

**Issue by pgleeson** [openworm/Blender2NeuroML#13]
That should run in python 2

Add test on  WrlToNeuroML.py  to actions

**Comment by TC-Wheel** [comment]
Haven't added WrlToNeuroML.py test yet. 
Though I changed PVDR to AVAR on my local. I didn't feel it was worthy of a merge until I got the python 3 scripts working.

**Comment by TC-Wheel** [comment]
already done days ago. 
This is included in the python3_update branch.
