### ISSUE TITLE
Remove *pyc files from repo and ignore rest

### ISSUE THREAD

**Issue by pgleeson** [openworm/Blender2NeuroML#8]

**Comment by TC-Wheel** [comment]
Should I actually just delete all .pyc files? What are the other parts that I'm ignoring?

**Comment by pgleeson** [comment]
Yes, see which ones are actually commited to the repo, then `git rm *.pyc` them. 

Adding a gitignore file (e.g. https://github.com/openworm/c302/blob/master/.gitignore) with *.pyc will mean no more show up as new files and can be accidentally added in a commit.

**Comment by TC-Wheel** [comment]
Finished on my branch. Should I merge with the master? (My commits are messy early on- but now that I've connected my gitbash and VS code- it'll be cleaner from now. I'm getting this down.)

**Comment by pgleeson** [comment]
Hi @TC-Wheel. Thanks. Please open a pull request from your branch to master and I'll have a look.

In general, it's best to close issues when the fixes get merged to master. An easy way to do this is just add soemthing like:

Fixes #10 

to the comment in the pull request, referring to the issue, and it will get closed automatically on merging.

**Comment by TC-Wheel** [comment]
Just created the pull request.
